const themeData = [
  { theme: "light" },
  { theme: "dark" },
  { theme: "cupcake" },
  { theme: "bumblebee" },
  { theme: "emerald" },
  { theme: "corporate" },
  { theme: "synthwave" },
  { theme: "retro" },
  { theme: "cyberpunk" },
  { theme: "valentine" },
  { theme: "halloween" },
  { theme: "garden" },
  { theme: "forest" },
  { theme: "aqua" },
  { theme: "lofi" },
  { theme: "pastel" },
  { theme: "fantasy" },
  { theme: "wireframe" },
  { theme: "black" },
  { theme: "luxury" },
  { theme: "dracula" },
  { theme: "cmyk" },
  { theme: "autumn" },
  { theme: "business" },
  { theme: "acid" },
  { theme: "lemonade" },
  { theme: "night" },
  { theme: "coffee" },
  { theme: "winter" },
];

export default themeData;
